# Site
title:              '<strong><larger>Michael Slugocki</larger> <br>
                     <small>(Ph.D. Candidate)</small></strong>'
bio:                '<strong>Computational Psychophysicist <br>
                     Department of Psychology, Neuroscience & Behaviour <br>
                     McMaster University'
description:        'Computational Psychophysicist</strong>'
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo.jpg'
about_logo:         'assets/img/logo_about.jpg'
background:         'assets/img/background.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                www.slugocm.ca
#url:                http://127.0.0.1:4000
#email:              slugocm@mcmaster.ca


# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   Mike

# Social
# if you don't have any of social below, comment the line.
google:
  plus:            '111592013376790364447'
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
#email:
twitter:            slugocm
# facebook:           username
github-url:         slugocm
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin:           michael-slugocki-35b44190
#xing:              username
# instagram:          username
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
# steam:              username
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
